stages:
  - build
  - deploy

build-backend:
  stage: build
  tags:
    - local-shell
  script:
    - docker build -t backend .

deploy-backend:
  stage: deploy
  tags:
    - local-shell
  script:
    - cd "/home/igolovkodev/aston course git/igolovkodev-aston_devops_10/task8"
    - docker compose up -d --force-recreate backend
  only:
    - main
    - develop